-- Every option once, by dotted key: drives validation, the generated docs table and the settings UI.
local M = {}

M.options = {
  {
    key = "width",
    type = "number",
    default = 28,
    integer = true,
    min = 8,
    label = "Width",
    group = "layout",
    help = "sidebar width in cells",
  },
  {
    key = "dim_inactive_panes",
    type = "boolean",
    default = false,
    label = "Dim inactive panes",
    group = "layout",
    help = "let wezterm dim whichever pane is idle, sidebar included",
  },
  {
    key = "position",
    type = "enum",
    default = "left",
    enum = { "left", "right" },
    label = "Position",
    group = "layout",
    help = "which side the sidebar sits on",
  },
  {
    key = "collapsed",
    type = "enum",
    default = "rail",
    enum = { "rail", "hidden" },
    label = "Collapsed",
    group = "layout",
    help = "what the toggle collapses to",
  },
  {
    key = "rail_width",
    type = "number",
    default = 5,
    integer = true,
    min = 3,
    label = "Rail width",
    group = "layout",
    help = "rail width in cells; widened to the macOS button reserve",
  },
  {
    key = "rail_titlebar",
    type = "enum",
    default = "widen",
    enum = { "widen", "band", "none" },
    label = "Rail title bar",
    group = "layout",
    help = "macOS window buttons: widen the rail, band the window, or neither",
  },
  {
    key = "hide_native_tab_bar",
    type = "boolean",
    default = true,
    label = "Hide native tab bar",
    group = "layout",
    help = "sets `enable_tab_bar = false`",
  },
  {
    key = "poll_ms",
    type = "number",
    default = 500,
    integer = true,
    min = 50,
    label = "Poll interval",
    group = "behaviour",
    help = "upper bound for `status_update_interval`; drives the refresh",
  },
  {
    key = "padding",
    type = "table",
    container = true,
    shown = "`{ top = 1, left = 2, right = 1 }`",
    label = "Padding",
    group = "layout",
    values = "`{ top, left, right }`",
    help = "cells of padding inside the sidebar; `top` is added to the top strip",
  },
  {
    key = "padding.top",
    type = "number",
    default = 1,
    integer = true,
    min = 0,
    docs = false,
    label = "Padding top",
    group = "layout",
  },
  {
    key = "padding.left",
    type = "number",
    default = 2,
    integer = true,
    min = 0,
    docs = false,
    label = "Padding left",
    group = "layout",
  },
  {
    key = "padding.right",
    type = "number",
    default = 1,
    integer = true,
    min = 0,
    docs = false,
    label = "Padding right",
    group = "layout",
  },
  {
    key = "edge_to_edge",
    type = "boolean",
    default = true,
    label = "Edge to edge",
    group = "layout",
    help = "zero wezterm's window padding on the sides the sidebar touches",
  },
  {
    key = "tab_height",
    type = "enum",
    default = "card",
    enum = { "card", "row", "tall" },
    alias = { [3] = "tall", [2] = "card", [1] = "row", [true] = "card", [false] = "row" },
    label = "Card height",
    group = "cards",
    values = '`"card"` (`2`) \\| `"row"` (`1`) \\| `"tall"` (`3`)',
    help = "painted rows per tab",
  },
  {
    key = "meta",
    type = "enum",
    default = false,
    enum = { "auto", "cwd", "process", false },
    alias = { [true] = "auto" },
    label = "Meta line",
    group = "cards",
    values = '`"auto"` \\| `"cwd"` \\| `"process"` \\| `false`',
    help = "what the second card row shows",
  },
  {
    key = "meta_sep",
    type = "string",
    default = "  ",
    label = "Meta separator",
    group = "cards",
    help = "between the process and the path on the meta line",
  },
  {
    key = "row_gap",
    type = "number",
    default = 1,
    integer = true,
    min = 0,
    label = "Row gap",
    group = "cards",
    help = "blank rows after each card; part of the card's click target",
  },
  {
    key = "new_tab_button",
    type = "enum",
    default = "ghost",
    enum = { "ghost", "row", false },
    alias = { [true] = "ghost" },
    label = "New tab button",
    group = "chrome",
    values = '`"ghost"` \\| `"row"` \\| `false`',
    help = "how the new-tab affordance is drawn",
  },
  {
    key = "new_tab_label",
    type = "string",
    default = "New tab",
    label = "New tab label",
    group = "chrome",
    help = "label inside the new-tab card",
  },
  {
    key = "corners",
    type = "enum",
    default = "chamfer",
    enum = { "chamfer", "square" },
    label = "Corners",
    group = "cards",
    help = "card corner treatment",
  },
  {
    key = "frame",
    type = "any",
    default = false,
    open = true,
    label = "Frame",
    group = "layout",
    help = "inset the sidebar, leaving a gutter column in the content colour",
  },
  {
    key = "titlebar",
    type = "enum",
    default = "auto",
    enum = { "auto", "integrate", "plain", "macos" },
    label = "Title bar",
    group = "chrome",
    help = 'reserve cells for the macOS traffic lights; `"macos"` forces the reserve anywhere',
  },
  {
    key = "context",
    type = "enum",
    default = "popover",
    enum = { "popover", false },
    label = "Context menu",
    group = "behaviour",
    values = '`"popover"` \\| `false`',
    help = "right-click behaviour",
  },
  {
    key = "popover",
    type = "table",
    container = true,
    shown = '`{ width = "auto", follow_pointer = true, fade_ms = 90, overflow = "clip" }`',
    label = "Popover",
    group = "behaviour",
    values = "see below",
    help = "the action menu's width, hover, fade and overflow",
  },
  {
    key = "popover.width",
    type = "any",
    default = "auto",
    docs = false,
    label = "Popover width",
    group = "behaviour",
  },
  {
    key = "popover.follow_pointer",
    type = "boolean",
    default = true,
    docs = false,
    label = "Popover follows the pointer",
    group = "behaviour",
  },
  {
    key = "popover.fade_ms",
    type = "number",
    default = 90,
    integer = true,
    min = 0,
    max = 400,
    docs = false,
    label = "Popover fade",
    group = "behaviour",
  },
  {
    key = "popover.overflow",
    type = "enum",
    default = "clip",
    enum = { "clip", "grow" },
    docs = false,
    label = "Popover overflow",
    group = "behaviour",
  },
  {
    key = "strip_actions",
    type = "list",
    of = "enum",
    enum = { "toggle", "new_tab", "settings", "search" },
    default = { "toggle", "new_tab" },
    shown = '`{ "toggle", "new_tab" }`',
    label = "Strip actions",
    group = "chrome",
    values = '`"toggle"` \\| `"new_tab"` \\| `"settings"` \\| `"search"` \\| `{ id, icon, on_click }`',
    help = "icon buttons in the top strip, in the order given",
  },
  {
    key = "toggle_button",
    type = "boolean",
    default = true,
    label = "Toggle button",
    group = "chrome",
    help = "draw the collapse glyph in the top strip",
  },
  {
    key = "close_button",
    type = "enum",
    default = "hover",
    enum = { "hover", "always", "never" },
    label = "Close button",
    group = "cards",
    help = "when the close glyph is shown",
  },
  {
    key = "confirm_close",
    type = "boolean",
    default = true,
    label = "Confirm close",
    group = "behaviour",
    help = "let WezTerm prompt before closing stateful tabs",
  },
  {
    key = "debug",
    type = "boolean",
    default = false,
    label = "Debug logging",
    group = "behaviour",
    help = "log backend events and hit rows",
  },
  {
    key = "show_index",
    type = "boolean",
    default = false,
    label = "Show index",
    group = "cards",
    help = "prefix the tab index; on the meta line with 2-row cards",
  },
  {
    key = "pinned_style",
    type = "enum",
    default = "dense",
    enum = { "dense", "compact", "full" },
    label = "Pinned style",
    group = "cards",
    help = "how pinned entries are drawn",
  },
  {
    key = "separator",
    type = "enum",
    default = "gap",
    enum = { "rule", "gap", "none" },
    label = "Separator",
    group = "cards",
    help = "between the pinned block and the rest",
  },
  {
    key = "scroll_indicator",
    type = "enum",
    default = "auto",
    enum = { "auto", "always", "never" },
    alias = { [true] = "auto", [false] = "never" },
    label = "Scroll indicator",
    group = "chrome",
    values = '`"auto"` \\| `"always"` \\| `"never"` \\| `true` \\| `false`',
    help = "right-edge thumb when tabs overflow",
  },
  {
    key = "wheel",
    type = "enum",
    default = "scroll",
    enum = { "scroll", "switch" },
    label = "Wheel",
    group = "behaviour",
    help = "what the wheel does over the sidebar",
  },
  {
    key = "tear_off",
    type = "enum",
    default = true,
    enum = { true, false },
    alias = { edge = true },
    label = "Tear off",
    group = "behaviour",
    values = "`true` \\| `false`",
    help = "drop on the inner edge to move a tab to a new window",
  },
  {
    key = "adopt",
    type = "enum",
    default = "auto",
    enum = { "auto", true, false },
    label = "Adopt backend panes",
    group = "identity",
    values = '`"auto"` \\| `true` \\| `false`',
    help = "take over an unmapped pane carrying the title marker",
  },
  {
    key = "window_title",
    type = "boolean",
    default = true,
    label = "Window title",
    group = "chrome",
    help = "title the window after the content pane",
  },
  {
    key = "hover",
    type = "enum",
    default = "follow",
    enum = { "follow", "press" },
    label = "Hover",
    group = "behaviour",
    help = "when the sidebar holds focus",
  },
  {
    key = "hover_timeout_ms",
    type = "number",
    default = 6000,
    integer = true,
    min = 0,
    label = "Hover timeout",
    group = "behaviour",
    help = "clear the hover highlight after inactivity; `0` = never",
  },
  {
    key = "tooltip",
    type = "enum",
    default = "auto",
    enum = { "auto", "on", "off" },
    alias = { [true] = "on", [false] = "off" },
    label = "Tooltip",
    group = "behaviour",
    values = '`"auto"` \\| `true` \\| `false`',
    help = 'hover tooltip; `auto` needs `hover = "follow"`',
  },
  {
    key = "tooltip_delay_ms",
    type = "number",
    default = 600,
    integer = true,
    min = 0,
    label = "Tooltip delay",
    group = "behaviour",
    help = "hover dwell; effective delay is `max(this, poll_ms)`",
  },
  {
    key = "double_click_ms",
    type = "number",
    default = 400,
    integer = true,
    min = 0,
    label = "Double click",
    group = "behaviour",
    help = "double-click window on empty space",
  },
  {
    key = "animations",
    type = "enum",
    default = "auto",
    enum = { "auto", "on", "off" },
    alias = { [true] = "on", [false] = "off" },
    label = "Animations",
    group = "behaviour",
    values = '`"auto"` \\| `true` \\| `false`',
    help = "colour fades; the width still changes in one step",
  },
  {
    key = "animation",
    type = "table",
    container = true,
    docs = false,
    label = "Animation",
    group = "behaviour",
  },
  {
    key = "animation.fps",
    type = "number",
    default = 30,
    integer = true,
    min = 15,
    max = 60,
    label = "Animation fps",
    group = "behaviour",
    help = "backend frame rate for a fade",
  },
  {
    key = "animation.expand_ms",
    type = "number",
    default = 220,
    integer = true,
    min = 0,
    label = "Expand duration",
    group = "behaviour",
    help = "expand fade duration",
  },
  {
    key = "animation.collapse_ms",
    type = "number",
    default = 160,
    integer = true,
    min = 0,
    label = "Collapse duration",
    group = "behaviour",
    help = "collapse fade duration",
  },
  {
    key = "animation.hover",
    type = "boolean",
    default = false,
    label = "Animate hover",
    group = "behaviour",
    help = "animate hover transitions",
  },
  {
    key = "ellipsis",
    type = "string",
    default = "…",
    label = "Ellipsis",
    group = "cards",
    help = "used when truncating titles",
  },
  {
    key = "icons",
    type = "boolean",
    default = true,
    label = "Icons",
    group = "cards",
    help = "show process icons",
  },
  {
    key = "icon_map",
    type = "table",
    default = {},
    open = true,
    label = "Icon overrides",
    group = "cards",
    values = "table",
    help = "process name to glyph; also overrides UI glyphs",
  },
  {
    key = "title",
    type = "function",
    label = "Title hook",
    group = "hooks",
    values = "`fun(tab, pane): string`",
    help = "custom title: `fun(tab, pane): string`",
  },
  {
    key = "domain",
    type = "string",
    default = "CurrentPaneDomain",
    label = "Domain",
    group = "identity",
    help = "domain the sidebar pane is spawned in",
  },
  {
    key = "skip_close_confirmation",
    type = "boolean",
    default = true,
    label = "Skip close confirmation",
    group = "behaviour",
    help = "add `wez-vtabs` to the skip list",
  },
  {
    key = "private",
    type = "table",
    container = true,
    docs = false,
    label = "Private",
    group = "behaviour",
  },
  {
    key = "private.env",
    type = "table",
    default = { HISTFILE = "", fish_private_mode = "1", VTABS_PRIVATE = "1" },
    open = true,
    shown = '`{ HISTFILE = "", fish_private_mode = "1", VTABS_PRIVATE = "1" }`',
    label = "Private env",
    group = "behaviour",
    values = "table",
    help = "env for shells in private windows",
  },
  {
    key = "keys",
    type = "any",
    default = {},
    open = true,
    label = "Key overrides",
    group = "behaviour",
    values = "table \\| `false`",
    help = "key overrides; `false` disables all defaults",
  },
  {
    key = "theme",
    type = "table",
    container = true,
    open = true,
    shown = '`{ elevation = 0.06, split = "auto" }`',
    label = "Theme",
    group = "theme",
    values = "see Theme",
    help = "colour overrides",
  },
  {
    key = "theme.elevation",
    type = "number",
    default = 0.06,
    min = 0,
    max = 0.3,
    docs = false,
    label = "Elevation",
    group = "theme",
  },
  {
    key = "theme.split",
    type = "string",
    default = "auto",
    docs = false,
    label = "Split divider",
    group = "theme",
  },
  {
    key = "hooks",
    type = "table",
    default = {},
    container = true,
    docs = false,
    label = "Hooks",
    group = "hooks",
  },
  {
    key = "hooks.filter",
    type = "function",
    label = "Filter hook",
    group = "hooks",
    values = "`fun(tab, mux_window): boolean`",
    help = "hide tabs: `fun(tab, mux_window): boolean`",
  },
  {
    key = "hooks.footer",
    type = "function",
    label = "Footer hook",
    group = "hooks",
    values = "`fun(mux_window): rows`",
    help = "sticky bottom rows: `fun(mux_window): (string|FooterEntry)[]`",
  },
  {
    key = "hooks.theme",
    type = "function",
    label = "Theme hook",
    group = "hooks",
    values = "`fun(window, theme): theme`",
    help = "per-window theme: `fun(window, theme): theme`",
  },
  {
    key = "hooks.route",
    type = "function",
    label = "Route hook",
    group = "hooks",
    values = "`fun(meta): space_id`",
    help = "reserved for spaces; not called yet",
  },
  {
    key = "backend",
    type = "table",
    container = true,
    docs = false,
    label = "Backend",
    group = "backend",
  },
  {
    key = "backend.path",
    type = "any",
    label = "Backend path",
    group = "backend",
    values = "string \\| table \\| `fun(domain, host)`",
    help = "path to the `wez-vtabs` binary",
  },
  {
    key = "backend.repo",
    type = "string",
    default = "fredrir/wezterm-vertical-tabs",
    label = "Backend repo",
    group = "backend",
    help = "GitHub repo used for release downloads",
  },
  {
    key = "backend.version",
    type = "string",
    shown = "plugin version",
    label = "Backend version",
    group = "backend",
    help = "release tag to download",
  },
  {
    key = "backend.build",
    type = "boolean",
    default = true,
    label = "Backend build",
    group = "backend",
    help = "fall back to `cargo build` when no release matches",
  },
  {
    key = "backend.uservar",
    type = "string",
    default = "vtabs",
    label = "Backend user var",
    group = "backend",
    help = "user var name used by the backend",
  },
}

M.by_key = {}
for _, option in ipairs(M.options) do
  M.by_key[option.key] = option
end

---Walks a dotted key, creating tables on the way when `build` is set.
function M.at(tbl, key, build)
  local node = tbl
  local last = nil
  for part in key:gmatch "[^.]+" do
    if last then
      if node[last] == nil then
        if not build then
          return nil
        end
        node[last] = {}
      end
      node = node[last]
    end
    last = part
  end
  return node, last
end

function M.get(tbl, key)
  local node, last = M.at(tbl, key, false)
  return node and node[last]
end

function M.set(tbl, key, value)
  local node, last = M.at(tbl, key, true)
  node[last] = value
end

local function copy(value)
  if type(value) ~= "table" then
    return value
  end
  local out = {}
  for k, v in pairs(value) do
    out[k] = copy(v)
  end
  return out
end

---The default table, built from the schema so there is one source of truth.
function M.defaults()
  local out = {}
  for _, option in ipairs(M.options) do
    if option.default ~= nil then
      M.set(out, option.key, copy(option.default))
    end
  end
  return out
end

---True when `key` is inside an `open` container, whose children the schema does not enumerate.
function M.is_open(key)
  local prefix = nil
  for part in key:gmatch "[^.]+" do
    prefix = prefix and (prefix .. "." .. part) or part
    local option = M.by_key[prefix]
    if option and option.open and prefix ~= key then
      return true
    end
  end
  return false
end

return M
