[package]
name = "vtabs-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
vtabs-protocol.workspace = true
vtabs-engine.workspace = true
crossterm.workspace = true
serde_json.workspace = true

[dev-dependencies]
base64.workspace = true

[target.'cfg(unix)'.dependencies]
signal-hook.workspace = true
